/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'akarabae' at '21/03/18 17:08' with Gradle 3.0
 *
 * @author akarabae, @date 21/03/18 17:08
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
